In [5]:
import pandas as pd

df = pd.read_csv("Customer_Support_Training_Dataset.csv")

In [6]:
df.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26872 entries, 0 to 26871
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        26872 non-null  object
 1   instruction  26872 non-null  object
 2   category     26872 non-null  object
 3   intent       26872 non-null  object
 4   response     26872 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

In [8]:
df.describe(include = "all")

,flags,instruction,category,intent,response
count,26872,26872,26872,26872,26872
unique,394,24635,11,27,26870
top,BL,shipments to {{Delivery City}},ACCOUNT,edit_account,"Firstly, I truly understand how pivotal the {{..."
freq,5212,8,5986,1000,2

In [10]:
df.isnull().sum()

flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64

In [11]:
df['fallback'] = df['intent'].apply(
    lambda x: 1 if x.lower() in ['unknown', 'fallback', 'other'] else 0
)

In [12]:
df['resolved'] = df['fallback'].apply(lambda x: 0 if x == 1 else 1)

In [13]:
import numpy as np

df['fallback'] = df['intent'].apply(
    lambda x: 1 if x.lower() in ['unknown', 'fallback', 'other'] else 0
)

df['resolved'] = df.apply(
    lambda row: 0 if row['fallback'] == 1 else np.random.choice([0,1], p=[0.2, 0.8]),
    axis=1
)

In [14]:
df['conversation_id'] = (df.index // 3) + 1

In [16]:
import pandas as pd

df['timestamp'] = pd.date_range(
    start='2024-01-01',
    periods=len(df),
    freq='T'
)

/var/folders/wz/xkfm25ys1pzgjzd250_s_4800000gn/T/ipykernel_11255/1329366966.py:3: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df['timestamp'] = pd.date_range(

In [17]:
df.head()

,flags,instruction,category,intent,response,fallback,resolved,conversation_id,timestamp
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...,0,1,1,2024-01-01 00:00:00
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...,0,1,1,2024-01-01 00:01:00
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...,0,1,1,2024-01-01 00:02:00
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...,0,0,2,2024-01-01 00:03:00
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...,0,1,2,2024-01-01 00:04:00

In [18]:
df.rename(columns={
    'instruction': 'user_query',
    'response': 'bot_response'
}, inplace=True)

In [20]:
df.to_csv('chatbot_logs.csv', index=False)